#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import algo

def main():
    algo.init()

if __name__ == "__main__":
    try:
        main()
    except IOError as e:
        algo.error("Connection closed by server", 1)
    except Exception as e:
        algo.error("An error occured, please try again", 1)
